Fixed teamSwitcher issue
formzillion/formzillion-temp pull request #129
Opened 2023-04-26 20:39 UTC by punithraj06

2023-04-26 21:19 UTC, SwatiSwa requested changes

2023-04-26 21:19 UTC, SwatiSwa commented on apps/webapp/src/app/(portal)/layout.tsx
> +    <div>You session as Expired Please login again</div>
Please correct the typo.
"Your session is expired. Please login again."

2023-04-27 06:23 UTC, punithraj06 commented on apps/webapp/src/app/(portal)/layout.tsx
> +    <div>You session as Expired Please login again</div>
resolved

2023-04-27 06:41 UTC, AbdulWadudh approved these changes

2023-04-27 06:41 UTC, merged